### ISSUE TITLE
[Bug]: Graph Completion not working with Neptune, 0.53

### ISSUE THREAD

**Issue by dwlmt** [topoteretes/cognee#2265]
### Bug Description

When using Neptune analytics for both vector and graph search, it is failing for Graph Completion and related graph search types.

### Steps to Reproduce

When any Graph search type, like the following, is called.

```

# Search the knowledge graph to verify priming
    results = await cognee.search(
        query_text="What does GMV stand for?",
        query_type=SearchType.GRAPH_COMPLETION
    )
```

The model passes node_type into the underlying node_name through the Neptune search which causes and error:

```
 File "/home/ubuntu/miniconda3/envs/athena-agent-strands/lib/python3.13/site-packages/cognee/modules/retrieval/utils/node_edge_vector_search.py", line 164, in _run_single_search
    search_results = await asyncio.gather(*search_tasks)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/athena-agent-strands/lib/python3.13/site-packages/cognee/modules/retrieval/utils/node_edge_vector_search.py", line 181, in _search_single_collection
    return await vector_engine.search(
                 ~~~~~~~~~~~~~~~~~~~~^
        collection_name=collection_name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        node_name=node_name,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: NeptuneAnalyticsAdapter.search() got an unexpected keyword argument 'node_name'
```

### Expected Behavior

Search should work with GRAPH_COMPLETION and GRAPH_SUMMARY_COMPLETION search types.

### Actual Behavior

Search fails as show in error. Works though with RAG completion and vector-only search types. Also with TRIPLET_COMPLETION.

### Environment

0.53.1 Cognee with Neptune dependencies.
1.47.0 Neptune (serverless)

### Logs/Error Messages

```shell

```

### Pre-submission Checklist

- [x] I have searched existing issues to ensure this bug hasn't been reported already
- [x] I have provided a clear and detailed description of the bug
- [x] I have included steps to reproduce the issue
- [x] I have included my environment details

**Comment by dwlmt** [comment]
I'm also seing this error sometimes when indexing text, but I haven't been able to reproduce it yet. It could be related. The error seems obvious, though, in that it's not expecting the edge to be a bool value.

```
 File "/home/ubuntu/miniconda3/envs/athena-agent-strands/lib/python3.13/site-packages/cognee/modules/graph/utils/retrieve_existing_edges.py", line 81, in retrieve_existing_edges
    existing_edges_map[str(edge[0]) + str(edge[1]) + edge[2]] = True
                           ~~~~^^^
TypeError: 'bool' object is not subscriptable
```

**Comment by siillee** [comment]
Hey @dwlmt, thanks for raising this issue!

The Neptune adapter has not been updated with the latest changes we did in the past release, that's why these errors are happening. We will look into this! In the meantime, if you are looking for a hybrid vector/graph database to use with cognee, you can check out our FalkorDB [adapter](https://github.com/topoteretes/cognee-community/tree/main/packages/hybrid/falkordb) on our community repo, which has been updated with the latest changes.

Kind regards,

**Comment by Vasilije1990** [comment]
@siillee let's fix it, please open a ticket

**Comment by dwlmt** [comment]
Do you have a timeline for when this Neptune issue will be fixed?

**Comment by dwlmt** [comment]
I manually installed the dev branch, and now it's working with GRAPH_COMPLETION and Neptune.

**Comment by dwlmt** [comment]
I still get this error though sometimes when the pipeline saves. It seems there is still some type problem in reading some data:

```
 File "/home/ubuntu/miniconda3/envs/athena-agent-strands/lib/python3.13/site-packages/cognee/modules/graph/utils/retrieve_existing_edges.py", line 81, in retrieve_existing_edges
    existing_edges_map[str(edge[0]) + str(edge[1]) + edge[2]] = True
```

**Comment by dwlmt** [comment]
This is another warning that always seems to be present with Neptune, I'm submitted 10 so the 100 must be from internally to Cognee:

`2026-03-11T17:55:22.929401 [warning  ] Provided limit (100) is invalid (None, zero, negative, or exceeds maximum). Defaulting to limit=10. [NeptuneAnalyticsAdapter]`

**Comment by siillee** [comment]
Hey @dwlmt, we did merge some fixes, so that's why it worked on the dev branch, just fyi.

As for the last warning about the limit being 100, could you provide some more details how you produce it? Which search are you doing, which search type are you using, etc?

Thanks in advance!

**Comment by dwlmt** [comment]
The other issue looks fixed. I think just doing the search produces. I have seen the pipeline issue since updating in the last couple of days so this could be fixed as well. couldn't reproduce it just gave this error. So I assume is type issue with how things were indexed:
```

 existing_edges_map[str(edge[0]) + str(edge[1]) + edge[2]] = True

TypeError: 'bool' object is not subscriptable
```

**Comment by siillee** [comment]
Hey @dwlmt, I checked in a bit more detail. The limit of 100 in Neptune's search comes from the `wide_search_top_k` parameter in the `cognee.search()` function, which is there to limit the graph projection in certain scenarios, so we don't actually need to project the entire graph in case it is very large. This is the warning you see, and it's not an issue.

As for the rest, all issues should be fixed, definitely on the dev branch, but even in the latest release, 0.5.5.
Are you still having some issues? I didn't fully understand the last part.

**Comment by Vasilije1990** [comment]
Solved
